import { StyleSheet } from "react-native";
export const color = {
  bg: "#f6f7f2",
  ink: "#1c261b",
  muted: "#667064",
  line: "#dce3d8",
  green: "#2f6d3a",
  soft: "#edf5e7",
  warm: "#fff4df",
};
export const s = StyleSheet.create({
  stage: {
    flex: 1,
    backgroundColor: "#e9ede6",
    alignItems: "center",
    justifyContent: "center",
  },
  app: { flex: 1, width: "100%", maxWidth: 480, backgroundColor: color.bg },
  header: { padding: 20, flexDirection: "row", alignItems: "center", gap: 12 },
  title: { fontSize: 21, fontWeight: "700", color: color.ink },
  text: { fontSize: 15, lineHeight: 23, color: color.ink },
  muted: { fontSize: 13, lineHeight: 20, color: color.muted },
  home: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
    alignItems: "center",
    justifyContent: "center",
  },
  content: { padding: 16, paddingTop: 4, gap: 14, flexGrow: 1 },
  card: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
    padding: 18,
    borderRadius: 22,
    gap: 10,
  },
  row: { flexDirection: "row", gap: 10, alignItems: "center" },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  third: {
    width: "30%",
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 6,
    gap: 3,
  },
  homeLayout: { flex: 1, minHeight: 500, gap: 14 },
  homeActions: { flex: 1, minHeight: 150, alignItems: "stretch" },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
  },
  button: {
    backgroundColor: color.green,
    borderRadius: 15,
    paddingHorizontal: 14,
    paddingVertical: 13,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  secondary: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: color.line,
    borderRadius: 14,
    padding: 13,
    fontSize: 15,
    backgroundColor: "white",
    color: color.ink,
    minHeight: 48,
  },
  nav: {
    flexDirection: "row",
    paddingVertical: 12,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderColor: color.line,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    gap: 5,
    minHeight: 44,
    justifyContent: "center",
  },
  badge: {
    color: color.green,
    backgroundColor: color.soft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    fontSize: 12,
  },
  footer: {
    padding: 14,
    gap: 10,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderColor: color.line,
  },
  notice: { backgroundColor: color.warm, padding: 10 },
});
