import { StyleSheet } from "react-native";
export const color = {
  bg: "#f6f7f2",
  ink: "#1c261b",
  muted: "#667064",
  line: "#dce3d8",
  green: "#2f6d3a",
  soft: "#edf5e7",
  warm: "#fff4df",
};
export const s = StyleSheet.create({
  stage: {
    flex: 1,
    backgroundColor: "#e9ede6",
    alignItems: "center",
    justifyContent: "center",
  },
  webSafeArea: {
    alignItems: "center",
    justifyContent: "center",
  },
  nativeSafeArea: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  appViewport: {
    position: "relative",
    overflow: "hidden",
  },
  app: { flex: 1, width: "100%", maxWidth: 480, backgroundColor: color.bg },
  header: {
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: color.line,
  },
  title: { fontSize: 21, fontWeight: "700", color: color.ink },
  text: { fontSize: 15, lineHeight: 23, color: color.ink },
  muted: { fontSize: 13, lineHeight: 20, color: color.muted },
  home: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
    alignItems: "center",
    justifyContent: "center",
  },
  content: { padding: 16, paddingTop: 16, gap: 14, flexGrow: 1 },
  card: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
    padding: 18,
    borderRadius: 22,
    gap: 10,
  },
  row: { flexDirection: "row", gap: 10, alignItems: "center" },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  toolCard: {
    minHeight: 0,
    alignItems: "center",
    padding: 12,
    gap: 8,
  },
  toolCardNameArea: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  toolCardName: {
    width: "100%",
    color: color.ink,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "600",
    textAlign: "center",
    textAlignVertical: "center",
  },
  toolDeleteButton: {
    width: "100%",
    minHeight: 38,
    marginTop: "auto",
    borderWidth: 1,
    borderColor: "#c94a3a",
    borderRadius: 12,
    backgroundColor: "#fff4f1",
    alignItems: "center",
    justifyContent: "center",
  },
  toolDeleteButtonPressed: {
    backgroundColor: "#f9ddd7",
  },
  toolDeleteText: {
    color: "#a94232",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
  },
  allergyListCard: {
    gap: 12,
  },
  allergyRow: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 4,
  },
  allergyLabel: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  allergyBullet: {
    color: color.green,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "700",
  },
  allergyDeleteButton: {
    flexShrink: 0,
    minWidth: 58,
    minHeight: 34,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#c94a3a",
    borderRadius: 10,
    backgroundColor: "#fff4f1",
    alignItems: "center",
    justifyContent: "center",
  },
  homeLayout: { flex: 1, minHeight: 500, gap: 14 },
  homeActions: { flex: 1, minHeight: 170, alignItems: "stretch" },
  refrigeratorDoor: {
    position: "relative",
  },
  refrigeratorHandle: {
    position: "absolute",
    alignSelf: "center",
    left: "20%",
    width: "60%",
    height: 16,
    opacity: 0.52,
  },
  refrigeratorHandleTop: { top: -3 },
  refrigeratorHandleBottom: { bottom: -3 },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
  },
  button: {
    backgroundColor: color.green,
    borderRadius: 15,
    paddingHorizontal: 14,
    paddingVertical: 13,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buttonDisabled: { opacity: 0.55 },
  secondary: {
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: color.line,
  },
  buttonText: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "600",
    color: "white",
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: color.line,
    borderRadius: 14,
    padding: 13,
    fontSize: 15,
    backgroundColor: "white",
    color: color.ink,
    minHeight: 48,
    fontFamily: "SUIT-Regular",
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  usageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  usageInput: {
    width: 86,
    borderWidth: 1,
    borderColor: color.line,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 15,
    textAlign: "right",
    backgroundColor: "white",
    color: color.ink,
    fontFamily: "SUIT-Regular",
  },
  nav: {
    flexDirection: "row",
    paddingVertical: 12,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderColor: color.line,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    gap: 5,
    minHeight: 44,
    justifyContent: "center",
  },
  badge: {
    color: color.green,
    backgroundColor: color.soft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    fontSize: 12,
  },
  footer: {
    padding: 14,
    gap: 10,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderColor: color.line,
  },
  chatComposer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderTopWidth: 1,
    borderColor: color.line,
  },
  chatComposerInput: {
    flex: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: color.line,
    borderRadius: 14,
    paddingHorizontal: 13,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: "white",
    color: color.ink,
    minHeight: 48,
    fontFamily: "SUIT-Regular",
  },
  chatSendButton: {
    flexShrink: 0,
    minHeight: 48,
    borderRadius: 15,
    backgroundColor: color.green,
    alignItems: "center",
    justifyContent: "center",
  },
  notice: { backgroundColor: color.warm, padding: 10 },
});
