create schema if not exists recipe_catalog;

revoke all on schema recipe_catalog from public, anon, authenticated;

create table recipe_catalog.recipes (
  recipe_id text primary key,
  source text not null,
  source_name text not null,
  source_dataset text not null,
  source_recipe_id text not null,
  name text not null,
  summary text,
  cuisine text,
  category text not null,
  cooking_method text,
  cooking_time text,
  servings text,
  difficulty text,
  estimated_cost text,
  main_ingredient_category text,
  weight_g numeric,
  kcal numeric,
  carbs_g numeric,
  protein_g numeric,
  fat_g numeric,
  sodium_mg numeric,
  hashtag text,
  image_main_url text,
  image_cooking_url text,
  tip text,
  ingredients_raw text not null
);

create table recipe_catalog.ingredients (
  id bigint generated by default as identity primary key,
  recipe_id text not null
    references recipe_catalog.recipes(recipe_id) on delete cascade,
  source text not null,
  source_recipe_id text not null,
  ingredient_no integer not null,
  ingredient_group text not null,
  ingredient_raw text not null,
  ingredient_name text not null,
  normalized_name text not null,
  parent_ingredient text,
  amount text,
  search_key text not null,
  parse_status text not null,
  unique (recipe_id, ingredient_no)
);

create table recipe_catalog.steps (
  id bigint generated by default as identity primary key,
  recipe_id text not null
    references recipe_catalog.recipes(recipe_id) on delete cascade,
  source text not null,
  source_recipe_id text not null,
  step_no integer not null,
  source_step_no text not null,
  description text not null,
  description_raw text not null,
  image_url text,
  step_tip text,
  unique (recipe_id, step_no)
);

create index recipes_name_idx
  on recipe_catalog.recipes(name);

create index ingredients_recipe_id_idx
  on recipe_catalog.ingredients(recipe_id);

create index ingredients_normalized_name_recipe_id_idx
  on recipe_catalog.ingredients(normalized_name, recipe_id);

create index ingredients_parent_ingredient_recipe_id_idx
  on recipe_catalog.ingredients(parent_ingredient, recipe_id)
  where parent_ingredient is not null;

create index ingredients_search_key_recipe_id_idx
  on recipe_catalog.ingredients(search_key, recipe_id);

create index steps_recipe_id_idx
  on recipe_catalog.steps(recipe_id);

alter table recipe_catalog.recipes enable row level security;
alter table recipe_catalog.ingredients enable row level security;
alter table recipe_catalog.steps enable row level security;

revoke all on table
  recipe_catalog.recipes,
  recipe_catalog.ingredients,
  recipe_catalog.steps
from public, anon, authenticated;

revoke all on all sequences in schema recipe_catalog
from public, anon, authenticated;

alter default privileges in schema recipe_catalog
  revoke all on tables from public, anon, authenticated;

alter default privileges in schema recipe_catalog
  revoke all on sequences from public, anon, authenticated;

create or replace function public.import_recipe_catalog_batch(
  target_table text,
  rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  affected_rows integer;
begin
  if coalesce(current_setting('request.jwt.claim.role', true), '') <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;

  if rows is null
    or jsonb_typeof(rows) <> 'array'
    or jsonb_array_length(rows) = 0 then
    raise exception 'catalog rows must be a non-empty JSON array';
  end if;

  if jsonb_array_length(rows) > 500 then
    raise exception 'catalog batch exceeds 500 rows';
  end if;

  case target_table
    when 'recipes' then
      insert into recipe_catalog.recipes
      select record.*
      from jsonb_populate_recordset(
        null::recipe_catalog.recipes,
        rows
      ) as record
      on conflict (recipe_id) do update set
        source = excluded.source,
        source_name = excluded.source_name,
        source_dataset = excluded.source_dataset,
        source_recipe_id = excluded.source_recipe_id,
        name = excluded.name,
        summary = excluded.summary,
        cuisine = excluded.cuisine,
        category = excluded.category,
        cooking_method = excluded.cooking_method,
        cooking_time = excluded.cooking_time,
        servings = excluded.servings,
        difficulty = excluded.difficulty,
        estimated_cost = excluded.estimated_cost,
        main_ingredient_category = excluded.main_ingredient_category,
        weight_g = excluded.weight_g,
        kcal = excluded.kcal,
        carbs_g = excluded.carbs_g,
        protein_g = excluded.protein_g,
        fat_g = excluded.fat_g,
        sodium_mg = excluded.sodium_mg,
        hashtag = excluded.hashtag,
        image_main_url = excluded.image_main_url,
        image_cooking_url = excluded.image_cooking_url,
        tip = excluded.tip,
        ingredients_raw = excluded.ingredients_raw;

    when 'ingredients' then
      insert into recipe_catalog.ingredients (
        recipe_id,
        source,
        source_recipe_id,
        ingredient_no,
        ingredient_group,
        ingredient_raw,
        ingredient_name,
        normalized_name,
        parent_ingredient,
        amount,
        search_key,
        parse_status
      )
      select
        record.recipe_id,
        record.source,
        record.source_recipe_id,
        record.ingredient_no,
        record.ingredient_group,
        record.ingredient_raw,
        record.ingredient_name,
        record.normalized_name,
        record.parent_ingredient,
        record.amount,
        record.search_key,
        record.parse_status
      from jsonb_to_recordset(rows) as record(
        recipe_id text,
        source text,
        source_recipe_id text,
        ingredient_no integer,
        ingredient_group text,
        ingredient_raw text,
        ingredient_name text,
        normalized_name text,
        parent_ingredient text,
        amount text,
        search_key text,
        parse_status text
      )
      on conflict (recipe_id, ingredient_no) do update set
        source = excluded.source,
        source_recipe_id = excluded.source_recipe_id,
        ingredient_group = excluded.ingredient_group,
        ingredient_raw = excluded.ingredient_raw,
        ingredient_name = excluded.ingredient_name,
        normalized_name = excluded.normalized_name,
        parent_ingredient = excluded.parent_ingredient,
        amount = excluded.amount,
        search_key = excluded.search_key,
        parse_status = excluded.parse_status;

    when 'steps' then
      insert into recipe_catalog.steps (
        recipe_id,
        source,
        source_recipe_id,
        step_no,
        source_step_no,
        description,
        description_raw,
        image_url,
        step_tip
      )
      select
        record.recipe_id,
        record.source,
        record.source_recipe_id,
        record.step_no,
        record.source_step_no,
        record.description,
        record.description_raw,
        record.image_url,
        record.step_tip
      from jsonb_to_recordset(rows) as record(
        recipe_id text,
        source text,
        source_recipe_id text,
        step_no integer,
        source_step_no text,
        description text,
        description_raw text,
        image_url text,
        step_tip text
      )
      on conflict (recipe_id, step_no) do update set
        source = excluded.source,
        source_recipe_id = excluded.source_recipe_id,
        source_step_no = excluded.source_step_no,
        description = excluded.description,
        description_raw = excluded.description_raw,
        image_url = excluded.image_url,
        step_tip = excluded.step_tip;

    else
      raise exception 'unsupported catalog table';
  end case;

  get diagnostics affected_rows = row_count;
  return affected_rows;
end
$$;

revoke all on function public.import_recipe_catalog_batch(text, jsonb)
from public, anon, authenticated;

grant execute on function public.import_recipe_catalog_batch(text, jsonb)
to service_role;

create or replace function public.verify_recipe_catalog()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  recipe_count bigint;
  ingredient_count bigint;
  step_count bigint;
  ingredient_orphan_count bigint;
  step_orphan_count bigint;
  ingredient_duplicate_count bigint;
  step_duplicate_count bigint;
begin
  if coalesce(current_setting('request.jwt.claim.role', true), '') <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;

  select count(*) into recipe_count
  from recipe_catalog.recipes;

  select count(*) into ingredient_count
  from recipe_catalog.ingredients;

  select count(*) into step_count
  from recipe_catalog.steps;

  select count(*) into ingredient_orphan_count
  from recipe_catalog.ingredients as ingredient
  left join recipe_catalog.recipes as recipe
    on recipe.recipe_id = ingredient.recipe_id
  where recipe.recipe_id is null;

  select count(*) into step_orphan_count
  from recipe_catalog.steps as step
  left join recipe_catalog.recipes as recipe
    on recipe.recipe_id = step.recipe_id
  where recipe.recipe_id is null;

  select count(*) into ingredient_duplicate_count
  from (
    select ingredient.recipe_id, ingredient.ingredient_no
    from recipe_catalog.ingredients as ingredient
    group by ingredient.recipe_id, ingredient.ingredient_no
    having count(*) > 1
  ) as duplicate_ingredients;

  select count(*) into step_duplicate_count
  from (
    select step.recipe_id, step.step_no
    from recipe_catalog.steps as step
    group by step.recipe_id, step.step_no
    having count(*) > 1
  ) as duplicate_steps;

  return jsonb_build_object(
    'recipes', recipe_count,
    'ingredients', ingredient_count,
    'steps', step_count,
    'ingredient_orphans', ingredient_orphan_count,
    'step_orphans', step_orphan_count,
    'ingredient_duplicate_keys', ingredient_duplicate_count,
    'step_duplicate_keys', step_duplicate_count
  );
end
$$;

revoke all on function public.verify_recipe_catalog()
from public, anon, authenticated;

grant execute on function public.verify_recipe_catalog()
to service_role;
